### ISSUE TITLE
Dummy issue to include images in wiki

### ISSUE THREAD

**Issue by manuel-freire** [e-ucm/rage-analytics-realtime#14]
![realtime](https://cloud.githubusercontent.com/assets/2271676/18433512/47d0b368-78e8-11e6-815e-34dd57dd5a9e.png)
General architecture and where Realtime fits in

**Comment by crisal24** [comment]
![realtime_updated](https://cloud.githubusercontent.com/assets/19714314/19039451/4e1414b0-8980-11e6-8238-c9681919e8ff.png)

**Comment by RotaruDan** [comment]
![image1](https://user-images.githubusercontent.com/5658058/31728693-450e109a-b42d-11e7-9da9-d1aa36114606.png)
![image2](https://user-images.githubusercontent.com/5658058/31728694-452d4f5a-b42d-11e7-9ab7-d7a6e9b61cc6.png)

**Comment by RotaruDan** [comment]
![image1](https://user-images.githubusercontent.com/5658058/31728707-4e2f266e-b42d-11e7-83c4-084c483958af.png)
